Accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import Index,Login,Registro,salir,editarperfil,verperfil,cargaravatar,about,Posts,PostDetailView,Lista_de_categorias,BuscadorResultado, publicar_posts,MisPosts,EliminarPost,editar_post,ListaCategorias,EliminarCat,EditarCategoria,CrearCategoria
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    #Paginas 
    path('', Index.as_view(), name='index'),
    path('about/',about.as_view(),name='about'),
    # Login y registro 
    path('login/', Login.as_view(), name='login'),
    path('register/', Registro.as_view(), name='register'),
    path('index/', salir, name='salir'),
    path('editarperfil/', editarperfil.as_view(), name='editarperfil'),
    path ('perfil/', verperfil.as_view(), name="verperfil"),
    path ('cargaavatar/',cargaravatar, name="Avatar"),
    
    # Mostrar Posts y busquedas 
    path ('Blogs/', Posts, name='Blogs'),
    path ('Post/<slug:slug>', PostDetailView.as_view(), name="Post"),
    path ('categorias/<slug:slug>',Lista_de_categorias.as_view(), name="RCategoria"),
    path ('results/',BuscadorResultado.as_view(), name="buscar"),
    path ('Misposts/',MisPosts.as_view(), name="mispost"),

    # Funciones del Blog
    path ('publicar/',publicar_posts.as_view(), name="publicar"),
    path('eliminar/<slug:post_slug>/', EliminarPost.as_view(), name='eliminar_post'),
    path ('EditarPost/<int:post_id>//',editar_post.as_view(), name="editar_post" ),

    #Funciones Categorias
     path('ListaCategorias/', ListaCategorias.as_view(), name='lista_categorias'),
     path ('eliminarc/<slug:categoria_slug>/', EliminarCat.as_view(), name="eliminar_cat"),
    path('editar_categoria/<int:categoria_id>/', EditarCategoria.as_view(), name='editar_categoria'),
    path('crear-categoria/', CrearCategoria.as_view(), name='crear_categoria'),






]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Mimain/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Accounts.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.conf import settings

# Clase para guardar el Avatar
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
 
    def __str__(self):
        return f"{self.user} - {self.imagen}"

# Creamos la clase Post con título, un nombre en la url por cada post(slug), fecha de creacion, el autor que serán los usuarios y
# las categorias que un post puede tener muchas categorías y si el post es destacado o no
class Post (models.Model):
    titulo=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    resumen= models.CharField (max_length=300 , default='sin resumen')
    fecha= models.DateTimeField(auto_now_add=True)
    contenido=models.TextField (max_length=10000, default='sin contenido')
    autor=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    categoria=models.ManyToManyField('categorias',default="Sin categoria")
    destacado= models.BooleanField(default=False)
    imagen=models.ImageField(upload_to='Blog_image', null=True , blank=True)
    now_date=models.DateTimeField(default=timezone.now)

    class meta:
        ordering= ["-fecha"] # Para que muestre los ultimos blogs creados primeros

    def __str__ (self): 
        return self.titulo


    
# Creamos el modelo categoria

class Categorias (models.Model):
    titulo=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)

    class meta:
        verbose_name_plural= 'categorias'

    def __str__ (self): 
        return self.titulo

Accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User,AbstractUser
from django.db import models
from django import forms
from .models import Avatar,Post

# Formulario Para crear nuevos usuarios utilizando el modelo definido por Django User
class RegistroUsuario(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2','last_name','first_name']

# Formulario para editar perfil
class UserEdit(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'last_name', 'first_name']

# Formulario para cambiar el Avatar
class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = '__all__'  # Esto incluirá todos los campos del modelo Avatar en el formulario

Accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login,logout    
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView, CreateView
from django.db.models import Max
from django.urls import reverse_lazy
from django.views import generic,View
from .forms import RegistroUsuario, UserEdit , AvatarForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import Avatar,Post,Categorias
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.utils.text import slugify
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
import os

# Creo las vistas del Login y el redireccionamiento en caso de que el Login sea exitoso al index.
class Index (LoginRequiredMixin,TemplateView):
    template_name = 'Accounts/index.html'

class verperfil (LoginRequiredMixin,TemplateView):
    template_name = 'Accounts/verperfil.html'

class about(LoginRequiredMixin,TemplateView):
    template_name = 'Accounts/about.html'

class Login(LoginView):
    template_name = 'Accounts/login.html'
    redirect_authenticated_user = True  # Esto redirige a los usuarios autenticados
 # Esta función, si el usuario está autenticado, redirige a la página de inicio
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')
        return super().dispatch(request, *args, **kwargs)

# Creo la carga de formulario, si es valido guarda el usuario con los correspondientes datos
class Registro(FormView):
    template_name = 'Accounts/register.html'
    form_class = RegistroUsuario
    redirect_autheticated_user = True
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()
        user=form.save()
        if user is not None:
            login(self.request, user)
        return super(Registro, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
         return redirect('index')
        return super(Registro,self).get(*args, **kwargs)

# Log Out
def salir(request):
    logout(request)
    return redirect('index')

    # Editar Perfil:
class editarperfil(LoginRequiredMixin, FormView):
    template_name = 'Accounts/editarperfil.html'
    form_class = UserEdit
    success_url = reverse_lazy('verperfil')

    def form_valid(self, form):
        usuario = self.request.user
        informacion = form.cleaned_data
        usuario.email = informacion['email']
        usuario.set_password(informacion['password1'])
        usuario.last_name = informacion['last_name']
        usuario.first_name = informacion['first_name']
        usuario.save()

        return redirect ('verperfil')

    def get_initial(self):
        usuario = self.request.user
        return {'email': usuario.email, 'last_name': usuario.last_name, 'first_name': usuario.first_name}
    
# Formulario para cargar el Avatar, si el usuario ya posee uno se puede cambiar y se reemplaza.

@login_required
def cargaravatar(request):
    usuario = request.user
    if request.method == 'POST':
        miFormulario = AvatarForm(request.POST, request.FILES)
        if miFormulario.is_valid():
            avatares = Avatar.objects.filter(user=usuario)
            if avatares.exists():
                # Si existen avatares asociados al usuario, actualiza el primero encontrado
                avatar = avatares.first()
                avatar.imagen = miFormulario.cleaned_data['imagen']
                avatar.save()
            else:
                # Si no hay avatares, crea uno nuevo
                avatar = Avatar(user=usuario, imagen=miFormulario.cleaned_data['imagen'])
                avatar.save()

            # Redirigir a la página donde muestra el perfil
            return render(request, "Accounts/verperfil.html")  

    else:
        miFormulario = AvatarForm()
    
    return render(request, "Accounts/cargaavatar.html", {"miFormulario": miFormulario})


# Muestra los posts creados en la página Blog y muestra en el carrousel los primeros 3 destacados
@login_required
def Posts (request):
    posts= Post.objects.all().order_by('-fecha')
    lista_categorias=Categorias.objects.all()
    destacados=Post.objects.filter(destacado=True)[:3]
    context= { 
        'lista_post' :posts,
        'lista_categorias' : lista_categorias,
        'destacados' : destacados,
    }
    return render (request,"Accounts/blogs.html", context=context)

# Muestra en detalle el Post en una pagina
class PostDetailView (LoginRequiredMixin,generic.DetailView):
     model=Post
     template_name= 'Accounts/post_detalle.html'
    
    # Llamo las listas de categorías y Posts a todos los articulos
     def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['lista_categorias'] = Categorias.objects.all()
        context['lista_post'] = Post.objects.all().order_by('-fecha')
        return context
     

# Función para que se pueda enviar el nombre del titulo de categoria al buscador categorias.html
def obtener_titulo_categoria(path):
    query = path.replace('/categorias/', '')
    categoria = get_object_or_404(Categorias, slug=query)
    return categoria.titulo if categoria else None
     
# Clase creada para retornar los blogs por categoria 
class Lista_de_categorias(LoginRequiredMixin,generic.ListView):
    model= Post
    template_name= 'Accounts/categorias.html'

    def get_queryset(self):
        query = self.request.path.replace('/categorias/', '')
        print(query)
        post_list = Post.objects.filter(categoria__slug=query).filter(
            now_date__lte=timezone.now()).order_by('-fecha') 
        return post_list
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lista_categorias'] = Categorias.objects.all()
        context['categoria_titulo'] = obtener_titulo_categoria(self.request.path)
        return context
    
# Con esta función se buscara por titulo o por categoria en el buscador de index
class BuscadorResultado(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'Accounts/results.html'

    def get_queryset(self):
        query = self.request.GET.get('search')
         # Que contenga lo que busco  dentro del titulo o letras de las categorias
        post_list = Post.objects.filter(
            Q(titulo__icontains=query) | Q(categoria__titulo__icontains=query)
        ).filter(
            now_date__lte=timezone.now()
        ).distinct().order_by('-fecha')
        return post_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        context['categoria_titulo'] = Categorias.objects.all()
        context['query']= query
        return context
    
# Crear un nuevo Post

class publicar_posts(LoginRequiredMixin,View):
    template_name = 'Accounts/Publicar.html'
    success_url = reverse_lazy('Blogs')

    def get(self, request, *args, **kwargs):
        lista_categorias = Categorias.objects.all()
        return render(request, self.template_name, {'lista_categorias': lista_categorias})

    def post(self, request, *args, **kwargs):
        titulo = request.POST.get('titulo')
        contenido = request.POST.get('contenido')
        resumen = request.POST.get('resumen')
        categoria_id = request.POST.get('categoria')
        imagen = request.FILES.get('imagen')

        categoria = Categorias.objects.get(id=categoria_id)
        autor = self.request.user

        slug = slugify(titulo)

         # Verificar la unicidad del slug y hacerlo único si es necesario
        slug_original = slug
        i = 1
        while Post.objects.filter(slug=slug).exists():
            slug = f'{slug_original}-{i}'
            i += 1
        # Crear y guardar el nuevo post
        post = Post.objects.create(
            titulo=titulo,
            contenido=contenido,
            resumen=resumen,
            imagen=imagen,
            autor=autor,
            slug=slug
        )
        # Asignar la categoría al post usando el método set()
        post.categoria.set([categoria])

        return HttpResponseRedirect(self.success_url)
    

# Mostrar los Post de un determinado Usuario
class MisPosts(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = 'Accounts/Misposts.html'
    context_object_name = 'lista_post' 

    def get_queryset(self):
        # Filtrar los posts por el autor que sea el usuario autenticado actualmente
        return Post.objects.filter(autor=self.request.user).order_by('-fecha')

# Clase con función para eliminar los Post si el usuario es el autor.
class EliminarPost(View):
    def get(self, request, post_slug):
        post = get_object_or_404(Post, slug=post_slug)

        # Verificar si el usuario tiene permiso para eliminar el post
        if request.user != post.autor:
            return redirect('mispost') 

        # Si el usuario tiene permiso, elimina el post
        post.delete()
        return redirect('mispost')
    
# Editar Post

class editar_post (LoginRequiredMixin,View):

    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        lista_categorias = Categorias.objects.all()
        context = {
            'post': post,
            'lista_categorias': lista_categorias
        }
        return render(request, 'Accounts/EditarPost.html', context)
            
    def post(self, request, post_id):     
        post = Post.objects.get(id=post_id)

Accounts/templates/Accounts/Padre.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block titulo %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'Accounts/Page/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'Accounts/Page/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'Accounts/Page/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'Accounts/Page/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'Accounts/Page/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'Accounts/Page/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'Accounts/Page/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'Accounts/Page/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'Accounts/Page/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'Accounts/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

  <!-- Template Main CSS File -->
  <link href="{% static 'Accounts/Page/assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">Entrega Final </a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'index' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'about' %}">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'Blogs' %}">Blog</a></li>
          <li><a class="nav-link scrollto" href="{% url 'publicar' %}">Publicar</a></li>
          <li class="avatar2"> 
            {% if request.user.avatar_set.exists %}
            {% if request.user.avatar_set.first.imagen %}
                <img src="{{ request.user.avatar_set.first.imagen.url }}" class="rounded-circle" width="30px" alt="Avatar de {{ request.user.username }}">
            {% else %}
                <!-- Si no existe el objeto Avatar -->
            <img src="{% static 'Accounts/nonavatar.png' %}" alt="user" class="rounded-circle" width="31">
            {% endif %}
        {% else %}
            <!-- Si no existe el objeto Avatar -->
            <img src="{% static 'Accounts/nonavatar.png' %}" alt="user" class="rounded-circle" width="31">
        {% endif %}</li>
          <li class="dropdown scrollto"><a href="#" class="perfil"><span>{{request.user.username}} </span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% if user.is_superuser %}
              <li><a href="{% url 'lista_categorias' %}"> Categorias</a></li>
              {% endif %}
              <li><a href="{% url 'mispost' %}">Mis Posts</a></li>
              <li><a href="{% url 'editarperfil' %}">Editar Perfil</a></li>
              <li><a href="{% url 'verperfil' %}">Ver perfil</a></li>
               <li><a href="{% url 'salir' %}">Log Out</a></li>
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  {% block Main %}
 {% endblock %}
  <main id="main">

    <!-- ======= Clients Section ======= -->
    {% block bloque1 %}
    
  {% endblock %}
    <!-- End Cliens Section -->

    <!-- ======= About Us Section ======= -->
  {% block bloque2 %}
    
  {% endblock %}
    <!-- End About Us Section -->
    
    <!-- ======= Why Us Section ======= -->
    {% block bloque3 %}
    {% endblock %} 
    <!-- End Why Us Section -->
   
    <!-- ======= Team Section ======= -->
    {% block bloque4 %}
    {% endblock %}
    <!-- End Team Section -->
    <!-- ======= Pricing Section ======= -->
    {% block bloque5 %}
    
    {% endblock %}
    <!-- End Pricing Section -->

    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Funcionalidades de la Pagina</h2>
          <p> Para poder ingresar a cualquier parte de la página se deberá iniciar sesion dentro del login</p>
        </div>

        <div class="faq-list">
          <ul>
            <li data-aos="fade-up" data-aos-delay="100">
              <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1"> Sección Login y registro <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                <p>
                 En esta sección inicial permite al usuario registrarse, repitiendo su password para evitar que tenga errores de tipeo y a su vez teniendo una contraseña mayor a 8 caracteres
                 con mayusculas y números incluidos. Una vez registrado, el usuario puedo logear en la página principal y ver el resto del sitio.
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="200">
              <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-2" class="collapsed">La sección de editar perfil y avatar<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-2" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Esta sección permite modificar el nombre y apellido de cada uno de los usuarios registrados como también su email, dentro de esta se podrá ver un boton para acceder al cambio de imagen de perfil
                  que puede ser reemplazadas las veces que el usuario desee. 
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="300">
              <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-3" class="collapsed">La sección de Blog<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-3" class="collapse" data-bs-parent=".faq-list">
                <p>
                 En esta sección se visualizarán los distintos artículos escritos por los usuarios que se publicarán a través de la página publicar.
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="400">
              <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-4" class="collapsed">Publicar <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-4" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in.
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="500">
              <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-5" class="collapsed">Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-5" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque.
                </p>
              </div>
            </li>

          </ul>
        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->

    
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>Pablo Ehrhardt</span></strong>. Todos los derechos reservados
      </div>
      <div class="credits">
        Desarrollado por Pablo Ehrhardt
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'Accounts/Page/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'Accounts/Page/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'Accounts/Page/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'Accounts/Page/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'Accounts/Page/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'Accounts/Page/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'Accounts/Page/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'Accounts/Page/assets/js/main.js' %}"></script>

</body>

</html>

Accounts/templates/Accounts/cargaavatar.html
{% extends "Accounts/Padre.html" %}
{% load static %}

{% block titulo %} Editar perfil {% endblock %}

{% block Main %}
<section id="hero2" class="d-flex align-items-center">

  <div class="container">
    <div class="row">
    </div>
  </div>

</section>

<!-- End Hero -->

{% endblock %}

{% block bloque2 %}

<link href="{% static 'Accounts/Page/assets/css/account.css' %}" rel="stylesheet">
</head>
<body>
<div class="container-xl px-4 mt-4">


<hr class="mt-0 mb-4">
<div class="row">
	<div class="col-xl-4">
		<div class="card mb-4 mb-xl-0">
			<div class="card-header">Foto de perfil</div>
			<div class="card-body text-center">
				{% if request.user.avatar_set.exists %}
        {% if request.user.avatar_set.first.imagen %}
            <img src="{{ request.user.avatar_set.first.imagen.url }}" class="img-account-profile rounded-circle mb-2" alt="Avatar de {{ request.user.username }}">
        {% else %}
            <!-- Si existe el objeto Avatar pero no hay imagen asociada -->
            <p>No hay imagen asociada</p>
        {% endif %}
    {% else %}
        <!-- Si no existe el objeto Avatar -->
        <img src="{% static 'Accounts/nonavatar.png' %}" alt="user" class="img-account-profile rounded-circle mb-2">
    {% endif %}
				<div class="small font-italic text-muted mb-4">JPG or PNG hasta 5 MB</div>

        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{miFormulario.as_p}}
          <button type="">Guardar Cambios</button>
      </form>
			</div>
		</div>
	</div>

</div>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
	
</script>
	
	
{% endblock %}